import type { Course, Notation, Topic } from "./types";

const topic = (
  id: string,
  name: string,
  unit: Topic["unit"],
  methods: string[],
  typicalProblems: string[],
): Topic => ({ id, name, unit, methods, typicalProblems });

export const topics: Topic[] = [
  topic(
    "precalc-review",
    "Functions and precalculus review",
    "calc1",
    [
      "domain and range",
      "composition",
      "inverse functions",
      "exponent and log laws",
      "trig identities",
      "unit circle",
    ],
    [
      "find a composite function",
      "solve an exponential equation",
      "simplify a trig expression",
    ],
  ),
  topic(
    "limits",
    "Limits",
    "calc1",
    [
      "limit laws",
      "one-sided limits",
      "squeeze theorem",
      "infinite limits",
      "limits at infinity",
      "asymptotes",
    ],
    [
      "evaluate an algebraic limit",
      "find a one-sided limit",
      "locate an asymptote",
    ],
  ),
  topic(
    "continuity",
    "Continuity",
    "calc1",
    [
      "continuity at a point",
      "types of discontinuity",
      "Intermediate Value Theorem",
    ],
    ["test continuity", "classify a discontinuity", "apply the IVT"],
  ),
  topic(
    "epsilon-delta",
    "Precise definition of the limit",
    "calc1",
    ["epsilon-delta proofs"],
    ["prove a linear limit", "choose delta", "verify a limit definition"],
  ),
  topic(
    "derivative-definition",
    "The derivative as a limit",
    "calc1",
    [
      "definition of the derivative",
      "tangent lines",
      "rates of change",
      "differentiability vs continuity",
    ],
    [
      "differentiate from the definition",
      "find a tangent line",
      "compare average and instantaneous rates",
    ],
  ),
  topic(
    "differentiation-rules",
    "Differentiation rules",
    "calc1",
    [
      "power rule",
      "constant multiple rule",
      "sum rule",
      "product rule",
      "quotient rule",
      "chain rule",
    ],
    [
      "differentiate a polynomial",
      "use the product rule",
      "differentiate a composition",
    ],
  ),
  topic(
    "transcendental-derivatives",
    "Trig, exponential and log derivatives",
    "calc1",
    [
      "trig derivatives",
      "exponential derivatives",
      "log derivatives",
      "logarithmic differentiation",
    ],
    [
      "differentiate a trig product",
      "differentiate an exponential",
      "use logarithmic differentiation",
    ],
  ),
  topic(
    "implicit-differentiation",
    "Implicit differentiation",
    "calc1",
    ["implicit differentiation", "inverse trig derivatives"],
    [
      "find dy/dx implicitly",
      "find a tangent to a curve",
      "differentiate inverse trig",
    ],
  ),
  topic(
    "related-rates",
    "Related rates",
    "calc1",
    ["related-rates setup", "chain rule in time"],
    ["sliding ladder", "expanding circle", "filling cone"],
  ),
  topic(
    "linear-approximation",
    "Linearization and differentials",
    "calc1",
    ["tangent-line approximation", "differentials", "Taylor polynomials"],
    [
      "estimate a root",
      "estimate error with differentials",
      "build a Taylor polynomial",
    ],
  ),
  topic(
    "mvt",
    "Rolle's theorem and the Mean Value Theorem",
    "calc1",
    ["Rolle's theorem", "Mean Value Theorem", "monotonicity consequences"],
    [
      "verify MVT hypotheses",
      "find the guaranteed point",
      "bound a function change",
    ],
  ),
  topic(
    "extrema",
    "Extreme values",
    "calc1",
    [
      "critical points",
      "closed interval method",
      "first derivative test",
      "second derivative test",
    ],
    [
      "find absolute extrema",
      "classify a critical point",
      "use the closed interval method",
    ],
  ),
  topic(
    "curve-sketching",
    "Concavity and curve sketching",
    "calc1",
    ["concavity", "inflection points", "curve sketching"],
    ["make a sign chart", "find inflection points", "sketch from derivatives"],
  ),
  topic(
    "optimization",
    "Optimization",
    "calc1",
    ["constrained optimization"],
    ["maximize area", "minimize material", "optimize travel time"],
  ),
  topic(
    "lhopital",
    "Indeterminate forms and L'Hôpital's rule",
    "calc1",
    [
      "L'Hôpital's rule",
      "rewriting indeterminate products",
      "rewriting exponential forms",
    ],
    [
      "evaluate a 0/0 limit",
      "rewrite infinity minus infinity",
      "evaluate a 1 to infinity form",
    ],
  ),
  topic(
    "newtons-method",
    "Newton's method",
    "calc1",
    ["Newton iteration"],
    ["approximate a root", "perform two iterations", "analyze convergence"],
  ),
  topic(
    "antiderivatives",
    "Antiderivatives",
    "calc1",
    ["basic antiderivative rules", "initial-value problems"],
    [
      "find an antiderivative",
      "solve an initial-value problem",
      "recover position from velocity",
    ],
  ),
  topic(
    "riemann-ftc",
    "Definite integral and the FTC",
    "calc1",
    [
      "Riemann sums",
      "definite integral properties",
      "FTC Part 1",
      "FTC Part 2",
    ],
    [
      "write a Riemann sum",
      "differentiate an integral",
      "evaluate a definite integral",
    ],
  ),
  topic(
    "substitution",
    "u-substitution",
    "calc1",
    ["indefinite substitution", "definite substitution", "changing bounds"],
    ["integrate a composition", "change bounds", "choose a substitution"],
  ),
  topic(
    "numerical-integration",
    "Trapezoidal and Simpson's rules",
    "calc1",
    ["midpoint rule", "trapezoidal rule", "Simpson's rule", "error bounds"],
    [
      "approximate from a table",
      "apply Simpson's rule",
      "bound numerical error",
    ],
  ),
  topic(
    "integration-by-parts",
    "Integration by parts",
    "calc2",
    [
      "integration by parts",
      "repeated integration by parts",
      "cyclic integration by parts",
    ],
    ["integrate x e^x", "integrate a logarithm", "integrate e^x cos x"],
  ),
  topic(
    "trig-integrals",
    "Trigonometric integrals",
    "calc2",
    [
      "powers of sine and cosine",
      "powers of secant and tangent",
      "product-to-sum identities",
    ],
    [
      "integrate odd sine powers",
      "integrate secant powers",
      "use product-to-sum",
    ],
  ),
  topic(
    "trig-substitution",
    "Trigonometric substitution",
    "calc2",
    [
      "sine substitution",
      "tangent substitution",
      "secant substitution",
      "completing the square",
    ],
    [
      "integrate a radical",
      "complete the square",
      "draw the reference triangle",
    ],
  ),
  topic(
    "partial-fractions",
    "Partial fractions",
    "calc2",
    ["linear factors", "repeated factors", "irreducible quadratic factors"],
    [
      "decompose a rational function",
      "integrate repeated factors",
      "handle a quadratic factor",
    ],
  ),
  topic(
    "integration-strategy",
    "Choosing a technique",
    "calc2",
    ["integration strategy", "integral tables"],
    [
      "choose an integration method",
      "combine techniques",
      "use a table safely",
    ],
  ),
  topic(
    "improper-integrals",
    "Improper integrals",
    "calc2",
    ["infinite intervals", "unbounded integrands", "comparison test"],
    [
      "integrate over an infinite interval",
      "handle an endpoint singularity",
      "test convergence by comparison",
    ],
  ),
  topic(
    "area-between-curves",
    "Area between curves",
    "calc2",
    ["integrating with respect to x", "integrating with respect to y"],
    [
      "find enclosed area",
      "choose horizontal slices",
      "split at intersections",
    ],
  ),
  topic(
    "volumes",
    "Volumes",
    "calc2",
    ["slicing", "disks", "washers", "cylindrical shells"],
    [
      "rotate a region",
      "choose shells or washers",
      "find a cross-section volume",
    ],
  ),
  topic(
    "arc-length-surface-area",
    "Arc length and surface area",
    "calc2",
    ["arc length", "surfaces of revolution"],
    ["find curve length", "find surface area", "parameterize an arc"],
  ),
  topic(
    "applications-physics",
    "Work, average value, centre of mass",
    "calc2",
    ["work", "average value", "centre of mass"],
    ["pump fluid", "stretch a spring", "find a centroid"],
  ),
  topic(
    "differential-equations-intro",
    "Separable equations and models",
    "calc2",
    [
      "separable equations",
      "exponential growth and decay",
      "logistic models",
      "Newton's law of cooling",
      "direction fields",
    ],
    [
      "solve a separable equation",
      "fit a growth model",
      "solve a cooling problem",
    ],
  ),
  topic(
    "sequences",
    "Sequences",
    "calc2",
    ["limits of sequences", "monotone sequences", "bounded sequences"],
    ["find a sequence limit", "prove monotonicity", "use monotone convergence"],
  ),
  topic(
    "series-basics",
    "Series",
    "calc2",
    [
      "partial sums",
      "geometric series",
      "telescoping series",
      "divergence test",
    ],
    [
      "sum a geometric series",
      "telescope a series",
      "apply the divergence test",
    ],
  ),
  topic(
    "series-tests",
    "Convergence tests",
    "calc2",
    [
      "integral test",
      "p-series",
      "comparison test",
      "limit comparison test",
      "alternating series test",
      "absolute convergence",
      "ratio test",
      "root test",
    ],
    [
      "choose a convergence test",
      "classify conditional convergence",
      "bound alternating error",
    ],
  ),
  topic(
    "power-series",
    "Power series",
    "calc2",
    [
      "radius of convergence",
      "interval of convergence",
      "term-wise differentiation",
      "term-wise integration",
    ],
    [
      "find radius and interval",
      "differentiate a power series",
      "represent a function",
    ],
  ),
  topic(
    "taylor-series",
    "Taylor and Maclaurin series",
    "calc2",
    [
      "Taylor series",
      "Maclaurin series",
      "Lagrange remainder",
      "binomial series",
    ],
    [
      "find a Maclaurin series",
      "bound approximation error",
      "use a binomial series",
    ],
  ),
  topic(
    "parametric-polar",
    "Parametric curves and polar coordinates",
    "calc2",
    ["parametric derivatives", "parametric arc length", "polar area"],
    [
      "find a parametric tangent",
      "find polar area",
      "find parametric arc length",
    ],
  ),
  topic(
    "complex-numbers",
    "Complex numbers",
    "calc2",
    ["rectangular form", "polar form", "roots of complex numbers"],
    ["convert to polar form", "multiply complex numbers", "find roots"],
  ),
];

const notation: Notation = {
  inverseTrig: "arcsin",
  log: "ln",
  intervals: "interval",
  rationalizeDenominators: false,
};

const calc1 = topics
  .filter((item) => item.unit === "calc1" && item.id !== "epsilon-delta")
  .map((item) => item.id);
const honoursCalc1 = [...calc1.slice(0, 3), "epsilon-delta", ...calc1.slice(3)];
const calc2 = [
  "riemann-ftc",
  "substitution",
  ...topics.filter((item) => item.unit === "calc2").map((item) => item.id),
];
const scienceCalc2 = calc2.filter((id) => id !== "complex-numbers");
const lifeCalc1 = calc1.slice(0, calc1.indexOf("riemann-ftc") + 1);
const math31 = calc1.filter(
  (id) =>
    ![
      "epsilon-delta",
      "lhopital",
      "newtons-method",
      "numerical-integration",
    ].includes(id),
);

const course = (
  id: string,
  institution: string,
  code: string,
  name: string,
  level: Course["level"],
  topicOrder: string[],
  notes: string,
): Course => ({
  id,
  institution,
  code,
  name,
  level,
  topicOrder,
  notation,
  notes,
});

export const courses: Course[] = [
  course(
    "ualberta-math-100",
    "University of Alberta",
    "MATH 100",
    "Calculus for Engineering I",
    "calc1",
    calc1,
    "Engineering stream; includes numerical integration and Taylor polynomials.",
  ),
  course(
    "ualberta-math-101",
    "University of Alberta",
    "MATH 101",
    "Calculus for Engineering II",
    "calc2",
    calc2,
    "Engineering stream; includes parametric curves and complex numbers.",
  ),
  course(
    "ualberta-math-117",
    "University of Alberta",
    "MATH 117",
    "Honors Calculus I",
    "calc1",
    honoursCalc1,
    "Proof-based; includes epsilon-delta arguments.",
  ),
  course(
    "ualberta-math-118",
    "University of Alberta",
    "MATH 118",
    "Honors Calculus II",
    "calc2",
    scienceCalc2,
    "Proof-based Calculus II.",
  ),
  course(
    "ualberta-math-134",
    "University of Alberta",
    "MATH 134",
    "Calculus for the Life Sciences I",
    "calc1",
    lifeCalc1,
    "Applications are framed in biology.",
  ),
  course(
    "ualberta-math-136",
    "University of Alberta",
    "MATH 136",
    "Calculus for the Life Sciences II",
    "calc2",
    scienceCalc2,
    "Calculus II with life-science applications.",
  ),
  course(
    "ualberta-math-144",
    "University of Alberta",
    "MATH 144",
    "Calculus for the Mathematical and Physical Sciences I",
    "calc1",
    calc1,
    "Standard science stream; default course.",
  ),
  course(
    "ualberta-math-146",
    "University of Alberta",
    "MATH 146",
    "Calculus for the Mathematical and Physical Sciences II",
    "calc2",
    scienceCalc2,
    "Standard science Calculus II.",
  ),
  course(
    "ualberta-math-154",
    "University of Alberta",
    "MATH 154",
    "Calculus for Business and Economics I",
    "calc1",
    calc1.filter((id) => id !== "trig-substitution"),
    "Economics applications with lighter trigonometry.",
  ),
  course(
    "ualberta-math-156",
    "University of Alberta",
    "MATH 156",
    "Calculus for Business and Economics II",
    "calc2",
    scienceCalc2.filter(
      (id) =>
        !["trig-integrals", "trig-substitution", "parametric-polar"].includes(
          id,
        ),
    ),
    "Business and economics applications.",
  ),
  course(
    "ualberta-math-114",
    "University of Alberta",
    "MATH 114",
    "Elementary Calculus I (legacy)",
    "calc1",
    calc1,
    "Legacy code; follows the MATH 144 method set.",
  ),
  course(
    "ualberta-math-115",
    "University of Alberta",
    "MATH 115",
    "Elementary Calculus II (legacy)",
    "calc2",
    scienceCalc2,
    "Legacy code; follows the MATH 146 method set.",
  ),
  course(
    "ucalgary-math-249",
    "University of Calgary",
    "MATH 249",
    "Introductory Calculus",
    "calc1",
    calc1,
    "No high-school calculus assumed.",
  ),
  course(
    "ucalgary-math-265",
    "University of Calgary",
    "MATH 265",
    "University Calculus I",
    "calc1",
    calc1,
    "Assumes Alberta Mathematics 31.",
  ),
  course(
    "ucalgary-math-267",
    "University of Calgary",
    "MATH 267",
    "University Calculus II",
    "calc2",
    scienceCalc2,
    "Several-variable material is outside CalcTutor's scope.",
  ),
  course(
    "ucalgary-math-275",
    "University of Calgary",
    "MATH 275",
    "Calculus for Engineers and Scientists",
    "both",
    [...calc1, ...calc2.filter((id) => !calc1.includes(id))],
    "Compressed Calculus I and II.",
  ),
  course(
    "macewan-math-114",
    "MacEwan University",
    "MATH 114",
    "Elementary Calculus I",
    "calc1",
    calc1,
    "Course boundaries should be checked against the current calendar.",
  ),
  course(
    "macewan-math-115",
    "MacEwan University",
    "MATH 115",
    "Elementary Calculus II",
    "calc2",
    scienceCalc2,
    "Course boundaries should be checked against the current calendar.",
  ),
  course(
    "alberta-math-31",
    "Alberta high school",
    "Mathematics 31",
    "Calculus",
    "calc1",
    math31,
    "Lighter proof expectations and introductory integration.",
  ),
];

export const DEFAULT_COURSE_ID = "ualberta-math-144";

export const topicById = new Map(topics.map((item) => [item.id, item]));
export const courseById = new Map(courses.map((item) => [item.id, item]));
